<?php

namespace Bristolian\Service\EmailReceiver;

class MailgunEmailReceiver
{

}




/*


recipient   string  The recipient of the message as reported by MAIL TO during SMTP chat
sender  string  The sender of the message as reported by MAIL FROM during SMTP chat. Note: this value may differ from From MIME header
from    string  The sender of the message as reported by from message header, for example "Bob <bob@example.com>"
subject string  Subject string
Body-plain  string  The text version of the email. This field is always present. If the incoming message only has HTML body, Mailgun will create a text representation for you.
stripped-text   string  The text version of the message without quoted parts and signature block (if found)
stripped-signature  string  The signature block stripped from the plain text message (if found)
body-html   string  The HTML version of the message, if message was multipart. Note that all parts of the message will be posted, not just text/html. For instance, if a message arrives with "foo" part it will be posted as "body-foo"
stripped-html   string  The HTML version of the message, without quoted parts.
Attachment-count    int The number of attachments the message has.
Attachment-x    string  The attached file ('x' stands for number of the attachment). Attachments are handled as file uploads, encoded as multipart/form-data.
timestamp   int The number of seconds passed since January 1, 1970 (see securing web hooks)
token   string  A randomly generated string with a length of 50 (See securing webhooks)
signature   string  A string with hexadecimal digits generated by HMAC algorithm (see securing webhooks).
message-headers string  A list of MIME headers dumped to a JSON string (order of headers is preserved)
Content-id-map  string  JSON-encoded dictionary which maps Content-ID (CID) of each attachment to the corresponding attachment-x parameter. This allows you to map posted attachments to tags like <img src='cid'> in the message body.

*/
