version: "3"
services:
  installer:
    environment:
      - ENV_DESCRIPTION=default,prod
  js_and_css_prod_builder:
    build: containers/js_builder
    environment:
      # we don't set NODE_ENV as production, as that is for serving node requests, not building assets.
      - BRISTOLIAN_API_BASE_URL=https://api.bristolian.org
      - ENV_DESCRIPTION=default,prod
    entrypoint: ["bash", "/var/app/containers/js_builder/build_prod_assets.sh"]
    volumes:
      - .:/var/app
  php_fpm:
    environment:
      - ENV_DESCRIPTION=default,prod
  varnish:
    depends_on:
      - caddy
      - php_fpm
    ports:
      - "8008:80"
    environment:
      - ENV_DESCRIPTION=default,prod