version: "3"
services:
  db:
    ports:
      - "3306:3306"
  installer:
    env_file:
      - env_local_dev.env
  caddy:
#    env_file:
#      - env_local_dev.env
    ports:
      - "8000:80"
      - "8001:8001"
  js_builder:
    environment:
      - BRISTOLIAN_API_BASE_URL=http://local.api.bristolian.org
  php_fpm:
    env_file:
      - env_local_dev.env
  php_fpm_debug:
    env_file:
      - env_local_dev.env
  redis:
    ports:
      - "6379:6379"
  supervisord:
    ports:
      - "8002:8080"
  varnish:
    depends_on:
#      - nginx
      - php_fpm
      - php_fpm_debug
    ports:
      - "80:80"
    env_file:
      - env_local_dev.env


