version: "3"
services:
#  chrome:
#    ports:
#      - "9222:9222"
#    environment:
#      - CHROME_ARGS=--disable-web-security
  installer:
    environment:
      - ENV_DESCRIPTION=default,local
  nginx:
    environment:
      - ENV_DESCRIPTION=default,local
    ports:
      - "8000:8000"
      - "8001:8001"
  js_dev_builder:
    environment:
      - PHP_WEB_BUGS_BASE_URL=http://local.api.bristolian.org
  php_fpm:
    environment:
      - ENV_DESCRIPTION=default,local
  php_fpm_debug:
    environment:
      - ENV_DESCRIPTION=default,local
  redis:
    ports:
      - "6379:6379"
  supervisord:
    ports:
      - "8002:8080"
  varnish:
    depends_on:
      - nginx
      - php_fpm
      - php_fpm_debug
    ports:
      - "80:80"
    environment:
      - ENV_DESCRIPTION=default,local


