
FROM node:14.4.0-stretch-slim

WORKDIR /var/app

# RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y git

CMD sh /var/app/containers/sass_dev_builder/entrypoint.sh

# CMD tail -f /var/app/containers/npm/README_npm.md