<?php

namespace Bristolian\Model\Chat;

use Bristolian\FromString;
use Bristolian\ToString;

/**
 * A message generated by the system. Not sure if these being separate from UserChatMessages is correct.
 */
class SystemChatMessage
{
    use ToString;
    use FromString;

    public function __construct(
        public readonly int $id,
        //        public readonly string $user_id,
        public readonly string $room_id,
        public readonly string $text,
        public readonly int|null $reply_message_id,
        public readonly \DateTimeInterface $created_at,
    ) {
    }
}
