/**
 * PUT API helpers for setting tags on room files, links, and annotations.
 * These endpoints are not generated by generate:typescript_api_routes (no response type_info).
 */

export interface SetEntityTagsBody {
    tag_ids: string[];
}

function putTags(endpoint: string, body: SetEntityTagsBody): Promise<void> {
    return fetch(endpoint, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
    }).then((response: Response) => {
        if (response.status !== 200 && response.status !== 404) {
            throw new Error('Server failed to return an expected response.');
        }
        return response.json().then(() => undefined);
    });
}

export function setFileTags(room_id: string, file_id: string, body: SetEntityTagsBody): Promise<void> {
    return putTags(`/api/rooms/${room_id}/files/${file_id}/tags`, body);
}

export function setLinkTags(room_id: string, room_link_id: string, body: SetEntityTagsBody): Promise<void> {
    return putTags(`/api/rooms/${room_id}/links/${room_link_id}/tags`, body);
}

export function setAnnotationTags(room_id: string, room_annotation_id: string, body: SetEntityTagsBody): Promise<void> {
    return putTags(`/api/rooms/${room_id}/annotations/${room_annotation_id}/tags`, body);
}
