/**
 * PUT API helpers for setting tags on room files, links, and annotations.
 * These endpoints are not generated by generate:typescript_api_routes (no response type_info).
 */

export interface SetEntityTagsBody {
    tag_ids: string[];
}

function putTags(endpoint: string, body: SetEntityTagsBody): Promise<void> {
    return fetch(endpoint, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
    }).then((response: Response) => {
        if (response.status !== 200 && response.status !== 404) {
            throw new Error('Server failed to return an expected response.');
        }
        return response.json().then(() => undefined);
    });
}

export function setFileTags(room_id: string, file_id: string, body: SetEntityTagsBody): Promise<void> {
    return putTags(`/api/rooms/${room_id}/files/${file_id}/tags`, body);
}

export function setLinkTags(room_id: string, room_link_id: string, body: SetEntityTagsBody): Promise<void> {
    return putTags(`/api/rooms/${room_id}/links/${room_link_id}/tags`, body);
}

export function setAnnotationTags(room_id: string, room_annotation_id: string, body: SetEntityTagsBody): Promise<void> {
    return putTags(`/api/rooms/${room_id}/annotations/${room_annotation_id}/tags`, body);
}

export function setVideoTags(room_id: string, room_video_id: string, body: SetEntityTagsBody): Promise<void> {
    return putTags(`/api/rooms/${room_id}/videos/${room_video_id}/tags`, body);
}

export interface PatchRoomAnnotationBody {
    title: string;
    text: string;
}

/**
 * PATCH title + description text on a room annotation (not generated in api_routes).
 */
export function patchRoomAnnotation(
    room_id: string,
    room_annotation_id: string,
    body: PatchRoomAnnotationBody
): Promise<void> {
    return fetch(`/api/rooms/${room_id}/annotations/${room_annotation_id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
    }).then((response: Response) => {
        if (response.status === 404) {
            throw new Error('Annotation not found.');
        }
        if (response.status === 400) {
            return response.json().then((data: { data?: Record<string, string> }) => {
                const message = data.data && data.data['/title']
                    ? data.data['/title']
                    : (data.data && data.data['/text'] ? data.data['/text'] : 'Validation failed.');
                throw new Error(message);
            });
        }
        if (response.status !== 200) {
            throw new Error('Server failed to return an expected response.');
        }
        return response.json().then(() => undefined);
    });
}

export interface PatchRoomFileBody {
    description: string|null;
    note: string|null;
    /** Empty string clears the document date on the server. */
    document_timestamp: string;
}

/**
 * PATCH room file metadata (description, note, document date). Not generated in api_routes.
 */
export function patchRoomFile(
    room_id: string,
    file_id: string,
    body: PatchRoomFileBody
): Promise<void> {
    return fetch(`/api/rooms/${room_id}/files/${file_id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
    }).then((response: Response) => {
        if (response.status === 404) {
            throw new Error('File not found in room.');
        }
        if (response.status === 400) {
            return response.json().then((data: { data?: Record<string, string> }) => {
                const dataBlock = data.data;
                const message =
                    (dataBlock && dataBlock['/description']) ||
                    (dataBlock && dataBlock['/note']) ||
                    (dataBlock && dataBlock['/document_timestamp']) ||
                    'Validation failed.';
                throw new Error(message);
            });
        }
        if (response.status !== 200) {
            throw new Error('Server failed to return an expected response.');
        }
        return response.json().then(() => undefined);
    });
}

export interface PatchRoomDetailsBody {
    name: string;
    purpose: string;
}

function validationMessageFromJson(data: unknown): string {
    if (data !== null && typeof data === 'object') {
        const record = data as Record<string, unknown>;
        if (Array.isArray(record.errors) && record.errors.length > 0) {
            return String(record.errors[0]);
        }
        const inner = record.data;
        if (inner !== null && typeof inner === 'object') {
            const dataBlock = inner as Record<string, string>;
            const fromPath = dataBlock['/name'] ?? dataBlock['/purpose'];
            if (fromPath !== undefined && fromPath !== '') {
                return fromPath;
            }
        }
    }
    return 'Validation failed.';
}

/**
 * PATCH room display name and purpose (description). Not generated in api_routes.
 */
export function patchRoomDetails(room_id: string, body: PatchRoomDetailsBody): Promise<void> {
    return fetch(`/api/rooms/${room_id}/details`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
    }).then(async (response: Response): Promise<void> => {
        if (response.status === 404) {
            throw new Error('Room not found.');
        }
        if (response.status === 400) {
            const data: unknown = await response.json();
            throw new Error(validationMessageFromJson(data));
        }
        if (response.status !== 200) {
            throw new Error('Server failed to return an expected response.');
        }
        await response.json();
    });
}
