version: "3"
services:
  developing:
    build: containers/developing
    depends_on:
      - redis
    volumes:
      - .:/var/app
  php_test:
    build: containers/run_php_tests
    volumes:
      - .:/var/app
  phpcs:
    build: containers/run_php_codesniffer
    volumes:
      - .:/var/app
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    volumes:
      - ./config:/usr/local/etc
    command: ["redis-server", "/usr/local/etc/redis.conf"]






