
[program:whatdotheyknow_requested]
directory=/var/app
command=php cli.php service:whatdotheyknow_requested:continual
process_name=%(program_name)s_%(process_num)d
user=www-data
numprocs=1
autostart=true
autorestart=true
stdout_logfile=/var/app/data/supervisord/whatdotheyknow_requested_out.log
stdout_logfile_maxbytes=1MB
stderr_logfile=/var/app/data/supervisord/whatdotheyknow_requested_err.log
stderr_logfile_maxbytes=1MB
