server {
	server_name api.bristolian.org local.api.bristolian.org;

	root /var/home/Bristolian/Bristolian/containers/caddy;

	error_page 503 /maintenance.json;

	location / {
		return 503;
	}

	location = /maintenance.json {
		internal;
		default_type application/json;
	}

	add_header Retry-After 120 always;

    client_max_body_size 50M;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/basereality.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/basereality.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    access_log /var/log/nginx/access.bristolian.log timed_combined;
    error_log /var/log/nginx/error.bristolian.log;
}

server {
	server_name bristolian.org  *.bristolian.org;

	root /var/home/Bristolian/Bristolian/containers/caddy;

	error_page 503 /maintenance.html;

	location / {
		return 503;
	}

	location = /maintenance.html {
		internal;
	}

	add_header Retry-After 120 always;

    client_max_body_size 50M;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/basereality.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/basereality.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    access_log /var/log/nginx/access.bristolian.log timed_combined;
    error_log /var/log/nginx/error.bristolian.log;
}

server {
  if ($host = bristolian.org) {
    return 301 https://$host$request_uri;
  }

  client_max_body_size 50M;

  server_name *.bristolian.org bristolian.org;
  listen 80 default_server;
  return 404; # managed by Certbot
}
