<?php

// caption object

class Snippet
{
    use FromArray;

    private $videoId;//": string,
    private $lastUpdated;//": datetime,
    private $trackKind;//": string,
    private $language;//": string,
    private $name;//": string,
    private $audioTrackType;//": string,
    private $isCC;//": boolean,
    private $isLarge;//": boolean,
    private $isEasyReader;//": boolean,
    private $isDraft;//": boolean,
    private $isAutoSynced;//": boolean,
    private $status;//": string,
    private $failureReason;//": string
}

class Caption
{
    use FromArray;

    private string $kind; //": "youtube#caption",
    private string $etag;//": etag,
    private string $id; //": string,
    private Snippet $snippet;
}





// GET https://www.googleapis.com/youtube/v3/captions

class CaptionListRequest
{
    use FromArray;

    //The part parameter specifies the caption resource parts that the API response will include.
    private string $part;//	string

    //The id parameter specifies a comma-separated list of IDs that identify the caption resources that should be retrieved. Each ID must identify a caption track associated with the specified video.
    private string $videoId;
}

class CaptionListResponse
{
    use FromArray;

    private string $kind;//": "youtube#captionListResponse",
    private string $etag;//": etag,
    private array $items;//": [
        //caption Resource
    //]
}


class CaptionRequest
{

    private string $id;

    private string $tfmt = "vtt";
    //The tfmt parameter specifies that the caption track should be returned in a specific format. If the parameter is not included in the request, the track is returned in its original format.
    //
    //Supported values are:
    //sbv – SubViewer subtitle
    //scc – Scenarist Closed Caption format
    //srt – SubRip subtitle
    //ttml – Timed Text Markup Language caption
    //vtt – Web Video Text Tracks caption

    // the tlang parameter specifies that the API response should return a translation of the specified caption track. The parameter value is an ISO 639-1 two-letter language code that identifies the desired caption language. The translation is generated by using machine translation, such as Google Translate.
    // $tlang

}

class CaptionResponse
{
    // Content-Type header for the response is application/octet-stream.
}
